# Create Groups of 65 Images

In [5]:
in_path = r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\dicom\labels"
out_path = r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\dicom_groups\labels"

In [49]:
from glob import glob
import shutil
import os
import dicom2nifti
import nibabel as nib
import numpy as np

In [31]:
for patient in glob(in_path + "/*"):
    patient_name = os.path.basename(os.path.normpath(patient))
    number_folders = int(len(glob(patient + "/*")) / 64)

    for i in range(number_folders):
        output_path_name = os.path.join(out_path, patient_name + "_" + str(i))
        os.mkdir(output_path_name)

        for i, file in enumerate(glob(patient + "/*")):
            if i == 64 + 1:
                break

            shutil.move(file, output_path_name)

In [32]:
in_path = r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\dicom\images"
out_path = r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\dicom_groups\images"

In [33]:
for patient in glob(in_path + "/*"):
    patient_name = os.path.basename(os.path.normpath(patient))
    number_folders = int(len(glob(patient + "/*")) / 64)

    for i in range(number_folders):
        output_path_name = os.path.join(out_path, patient_name + "_" + str(i))
        os.mkdir(output_path_name)

        for i, file in enumerate(glob(patient + "/*")):
            if i == 64 + 1:
                break

            shutil.move(file, output_path_name)

---

# Convert Dicom Files to Nifties

In [42]:
in_path_images =  r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\dicom_groups\images\*"
in_path_labels =  r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\dicom_groups\labels\*"
out_path_images = r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\images"
out_path_labels = r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels"

list_images = glob(in_path_images)
list_labels = glob(in_path_labels)

In [43]:
for patient in list_images:
    patient_name = os.path.basename(os.path.normpath(patient))
    dicom2nifti.dicom_series_to_nifti(patient, os.path.join(out_path_images, patient_name + ".nii.gz"))

In [45]:
for patient in list_labels:
    patient_name = os.path.basename(os.path.normpath(patient))
    dicom2nifti.dicom_series_to_nifti(patient, os.path.join(out_path_labels, patient_name + ".nii.gz"))

---

# Find Empty

##### Some slices don't have labels, and they are useless, these cound as empty.

In [53]:
input_file_path = r"C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\*"
list_labels = glob(input_file_path)

for patient in list_labels:
    nifti_file = nib.load(patient)
    f_data = nifti_file.get_fdata()
    unique_pixels = np.unique(f_data)
    print(unique_pixels)

    if len(unique_pixels) == 1:
        # no label
        print(patient)

[0. 1. 2.]
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_10_0.nii.gz
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_10_1.nii.gz
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_10_2.nii.gz
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_10_3.nii.gz
[0. 1.]
[0. 1. 2.]
[0. 1. 2.]
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_11_0.nii.gz
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_11_1.nii.gz
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_11_2.nii.gz
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_11_3.nii.gz
[0. 1. 2.]
[0. 1. 2.]
[0. 1. 2.]
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_12_0.nii.gz
[0.]
C:\Users\MSI\Desktop\Medical_CT_Liver\Task03_Liver\nifti_files\labels\liver_12_1.nii